_target_: tali.models.auto_builder.transformers.AutoCLIPResNet
config:
  vision_layers:
  - 3
  - 4
  - 6
  - 3
  embedding_output_features: 512
  image_resolution:
    - ${datamodule.dataset_config.image_shape.width}
    - ${datamodule.dataset_config.image_shape.height}
